      - ip: 74.125.99.230
        domain: r1---sn-4g57knz7.googlevideo.com
      - ip: 74.125.99.231
        domain: r2---sn-4g57knz7.googlevideo.com
      - ip: 74.125.99.232
        domain: r3---sn-4g57knz7.googlevideo.com
      - ip: 74.125.99.233
        domain: r4---sn-4g57knz7.googlevideo.com
      - ip: 74.125.99.234
        domain: r5---sn-4g57knz7.googlevideo.com
      - ip: 74.125.99.235
        domain: r6---sn-4g57knz7.googlevideo.com
      - ip: 74.125.99.236
        domain: r7---sn-4g57knz7.googlevideo.com
      - ip: 74.125.99.237
        domain: r8---sn-4g57knz7.googlevideo.com
      - ip: 74.125.99.238
        domain: r9---sn-4g57knz7.googlevideo.com
      - ip: 74.125.99.239
        domain: r10---sn-4g57knz7.googlevideo.com
      - ip: 74.125.99.240
        domain: r11---sn-4g57knz7.googlevideo.com
      - ip: 74.125.99.241
        domain: r12---sn-4g57knz7.googlevideo.com
      - ip: 74.125.99.242
        domain: r13---sn-4g57knz7.googlevideo.com
      - ip: 74.125.99.243
        domain: r14---sn-4g57knz7.googlevideo.com
      - ip: 74.125.99.244
        domain: r15---sn-4g57knz7.googlevideo.com
      - ip: 74.125.99.245
        domain: r16---sn-4g57knz7.googlevideo.com
      - ip: 74.125.99.246
        domain: r17---sn-4g57knz7.googlevideo.com
      - ip: 74.125.99.247
        domain: r18---sn-4g57knz7.googlevideo.com
      - ip: 74.125.99.248
        domain: r19---sn-4g57knz7.googlevideo.com
      - ip: 74.125.99.249
        domain: r20---sn-4g57knz7.googlevideo.com
